test:
	go test -run TestRouter
	go test -run TestHealthSvr
	go test -run TestDiscoverSvr

many-router:
	go test -run TestManyRouter -timeout 30m

many-instance:
	go test -run TestManyInstance

many-discovery:
	go test -run TestManyDiscovery
