global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'etcd'
    static_configs:
      - targets: [
        '127.0.0.1:2381',
        '127.0.0.1:2481',
        '127.0.0.1:2581',

        '127.0.0.1:10000',
      ]